name: Bug 报告
description: 报告一个问题帮助我们改进
title: "[BUG] "
labels: ["bug"]
assignees:
  - username
body:
  - type: markdown
    attributes:
      value: |
        ## 谢谢您的报告！
        请在提交之前，检查该问题是否已经被报告过。        
      
  - type: input
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 请尽可能详细地描述问题。
      placeholder: 请在这里输入详细信息
    validations:
      required: true
  
  - type: checkboxes
    id: terms
    attributes:
      label: 确认项
      description: 请确认以下信息。
      options:
        - label: 我已经搜索过了现有的issue，确信这个问题是新的。
          required: true
        - label: 我已经阅读了说明文档。
          required: false
  
  - type: input
    id: version
    attributes:
      label: 受影响的版本
      description: 请输入受影响的软件版本。
      placeholder: 在这里输入受影响的版本
    validations:
      required: true

