
["Item merge settings"]
	#Default: 1.25, Minecraft default: 0.5
	#Range: 0.5 ~ 10.0
	maxMergeDistanceHorizontal = 1.25
	#Default: 0.0, Minecraft default: 0.0
	#Range: 0.0 ~ 10.0
	maxMergeDistanceVertical = 0.0
	#Default: 2147483647
	#Range: > 1
	maxSize = 2147483647
	#Default: false
	enableForUnstackableItem = false
	#e.g., ["minecraft:diamond_block", "minecraft:coal"]
	itemBlackList = []

