
#List of entity configurations
[[entities]]
    entity = "blue_archivescraft:fire_2"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "cataclysm:ender_golem"
	minTier = 4
	maxTier = 4
	presetAffixes = ["adaptable"]
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "cataclysm:ender_guardian"
	minTier = 10
	maxTier = 10
	presetAffixes = ["adaptable", "enkinding", "magnetic", "Lively", "dampening", "arctic", "hasty", "reflective"]
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "cataclysm:ignis"
	minTier = 10
	maxTier = 10
	presetAffixes = ["enkinding", "adaptable", "magnetic", "Lively", "dampening", "arctic", "hasty", "reflective"]
	affixList = ["infested", "desecrating", "plagued", "arctic", "shielding"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "cataclysm:netherite_monstrosity"
	minTier = 10
	maxTier = 10
	presetAffixes = ["adaptable", "enkinding", "magnetic", "Lively", "dampening", "arctic", "hasty", "reflective"]
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "ob_aquamirae:drowned_captain"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:naga"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:lich"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:minoshroom"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:hydra"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:knight_phantom"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:ur_ghast"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:yeti_alpha"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:snow_queen"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:giant_miner"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "twilightforest:armored_giant"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "alexsmobs:void_worm"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "mowziesmobs:ferrous_wroughtnaut"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "mowziesmobs:barako"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "mowziesmobs:frostmaw"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "graveyard:lich"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "stalwart_dungeons:awful_ghast"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "stalwart_dungeons:nether_keeper"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "illagerinvasion:invoker"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:bloody_butcher"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:bloody_driver"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:bloody_driver"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:curse"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:iron_hit"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:prowler"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:walking_bed"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "sons_of_sins:wistiver"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "blue_skies:summoner"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "blue_skies:alchemist"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "blue_skies:arachnarch"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "blue_skies:starlit_crusher"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
	entity = "notsoshrimple:crayfish"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"

[[entities]]
    entity = "minecraft:wither"
	minTier = 4
	maxTier = 4
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten", "adaptable", "shielding"]
	affixPermission = "BLACKLIST"

[[entities]]
    entity = "ob_aquamirae:drowned_captain"
	minTier = 3
	maxTier = 3
	presetAffixes = []
	affixList = ["knocking", "wounding", "paralyzing", "molten"]
	affixPermission = "BLACKLIST"